apiVersion: v1
kind: ConfigMap
metadata:
  name: be-user-config
data:
  application-stg.yml: |
    server:
      port: 8080

    spring:
      datasource:
        url: jdbc:postgresql://52.78.117.85:5432/coubee_user
        driver-class-name: org.postgresql.Driver
        hikari:
          connection-test-query: SELECT 1
          validation-timeout: 5000
      
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update # 개발 환경용
        generate-ddl: true
        show-sql: true
        open-in-view: false
        properties:
          hibernate.default_schema: coubee_user
      kafka:
        bootstrap-servers: coubee-external-kafka-service:9092
      file:
        upload:
          base-dir: ${user.home}/Desktop/coubee-img
          resource-url: /images/**
    cloud:
      aws:
        region:
          static: ap-northeast-2
        s3:
          bucket: coubee-s3
        cloudfront:
          domain: d1du1htkbm5yt2.cloudfront.net